/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author lenovo
 */
public class addshop extends javax.swing.JFrame {
Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    String sql = null;
    PreparedStatement pst = null;
    /**
     * Creates new form addshop
     */
    public addshop() {
        initComponents();
        conn = connector.connectiondb();
        this.setLocationRelativeTo(null);
        addshop.setEnabled(false);
        ap.setVisible(false);
        
        ImageIcon myimage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("shop.png")));     
      Image img = myimage.getImage();
      Image img1 = img.getScaledInstance(myshop.getWidth(),myshop.getHeight(), Image.SCALE_SMOOTH);
      ImageIcon e = new ImageIcon(img1);
    myshop.setIcon(e);
    
    ImageIcon myimagea = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("approved.jpg")));     
      Image img2 = myimagea.getImage();
      Image img1x = img2.getScaledInstance(ap.getWidth(),ap.getHeight(), Image.SCALE_SMOOTH);
      ImageIcon es = new ImageIcon(img1x);
    ap.setIcon(es);
    
    try{
      Class.forName("com.mysql.jdbc.Driver");
      conn = DriverManager.getConnection("jdbc:mysql://localhost/savedme_db","root","");

            String sq = "select shopid  from shop order by shopid desc limit 1 ";
            pst = conn.prepareStatement(sq);           
            rs = pst.executeQuery();
            
            if(rs.next()){   
                
              String add1=rs.getString("shopid");
                             
                int sum=0;
                int a = Integer.parseInt(add1);
                sum=a+1;
                shopid.setText(Integer.toString(sum)); 
            }
            
        }catch (ClassNotFoundException | SQLException b)
        {
        }      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        myshop = new javax.swing.JLabel();
        shopid = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        shopname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        employee = new javax.swing.JTextField();
        contact = new javax.swing.JLabel();
        fullname = new javax.swing.JLabel();
        area = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        addshop = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ap = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 500, -1));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("+ Shop");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("X");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 20, -1));

        myshop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/shop.png"))); // NOI18N
        myshop.setText("shop");
        myshop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(myshop, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 70));

        shopid.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        shopid.setForeground(new java.awt.Color(255, 255, 255));
        shopid.setText("shop ID");
        shopid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(shopid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 84, 240, 30));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Shop ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Shop Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        shopname.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        shopname.setForeground(new java.awt.Color(0, 51, 255));
        shopname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(shopname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 330, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Employee's ID No.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        employee.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        employee.setForeground(new java.awt.Color(0, 51, 255));
        employee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        employee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                employeeKeyReleased(evt);
            }
        });
        jPanel1.add(employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 330, 30));

        contact.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        contact.setForeground(new java.awt.Color(255, 255, 255));
        contact.setText("Contact");
        jPanel1.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 380, 30));

        fullname.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        fullname.setForeground(new java.awt.Color(255, 255, 255));
        fullname.setText("Fullname");
        jPanel1.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 380, 30));

        area.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        area.setForeground(new java.awt.Color(0, 51, 255));
        area.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(area, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 330, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Area");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        addshop.setBackground(new java.awt.Color(255, 153, 0));
        addshop.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        addshop.setForeground(new java.awt.Color(255, 255, 255));
        addshop.setText("Complete");
        addshop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addshop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addshopActionPerformed(evt);
            }
        });
        jPanel1.add(addshop, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 170, 40));

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("| Go to List");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 5, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("GENERATE");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 80, 20));

        ap.setFont(new java.awt.Font("Tw Cen MT", 2, 24)); // NOI18N
        ap.setForeground(new java.awt.Color(153, 153, 153));
        ap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/approved.jpg"))); // NOI18N
        jPanel1.add(ap, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    private void addshopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addshopActionPerformed
        if(shopid.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "shop.ID is Required","Invalid",2);
        }
        if(shopname.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Name of the Shop is Required","Invalid",2);
        }
        if(employee.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Employee is Required","Invalid",2);
        }
        if(area.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Area is Required","Invalid",2);
        }

        else{
            try{

                String Sql= "INSERT INTO `shop`(`shopid`, `shopname`, `employee`, `area`) VALUES (?,?,?,?)";
                pst= conn.prepareStatement(Sql);
               

                pst.setString(1, shopid.getText());
                pst.setString(2, shopname.getText());
                pst.setString(3, employee.getText());
                pst.setString(4,area.getText());                              
                
                if(JOptionPane.showConfirmDialog(null,"Are you sure?","ADD A SHOP",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
       {
                pst.execute();

                JOptionPane.showMessageDialog(null,"Done.");

                shopid.setText("");
                shopname.setText("");
                employee.setText("");
                area.setText("");
                
                }
            else
       {
       }}

            catch(SQLException | HeadlessException e){
               JOptionPane.showMessageDialog(null, "Duplicate Shop.ID. Try to re-generate.","ERROR",2);
            }

        }
    }//GEN-LAST:event_addshopActionPerformed

    private void employeeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeKeyReleased
     if(employee.getText().equals(""))
        {
            fullname.setText("");
            contact.setText("");
            addshop.setEnabled(false);
        } 
     try{

            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/savedme_db","root","");

            String sq = "select concat(`fname`,' ',`mname`,' ',`lname`) as fullname, phone from people where id = ? and role = 'Employee' ";
            pst = conn.prepareStatement(sq);
            pst.setString(1, employee.getText());

            rs = pst.executeQuery();

            if(rs.next()){
                String add1=rs.getString("fullname");
                fullname.setText(add1);

                String add2=rs.getString("phone");
                contact.setText(add2);

                
                addshop.setEnabled(true);
                ap.setVisible(true);
            }
            else{
        
            fullname.setText("");
            contact.setText("");
            addshop.setEnabled(false);
            ap.setVisible(false);
            }

        }catch (Exception e)
        {JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_employeeKeyReleased

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
 try{
      Class.forName("com.mysql.jdbc.Driver");
      conn = DriverManager.getConnection("jdbc:mysql://localhost/savedme_db","root","");

            String sq = "select shopid  from shop order by shopid desc limit 1 ";
            pst = conn.prepareStatement(sq);           
            rs = pst.executeQuery();
            
            if(rs.next()){   
                
              String add1=rs.getString("shopid");
                             
                int sum=0;
                int a = Integer.parseInt(add1);
                sum=a+1;
                shopid.setText(Integer.toString(sum)); 
            }
            
        }catch (ClassNotFoundException | SQLException b)
        {
        }            // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        shoplist a = new shoplist();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addshop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addshop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addshop;
    private javax.swing.JLabel ap;
    private javax.swing.JTextField area;
    private javax.swing.JLabel contact;
    private javax.swing.JTextField employee;
    private javax.swing.JLabel fullname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel myshop;
    private javax.swing.JLabel shopid;
    private javax.swing.JTextField shopname;
    // End of variables declaration//GEN-END:variables
}
