/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static login.adminpanel.datas;
import static login.adminpanel.total;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author lenovo
 */
public class cash_in extends javax.swing.JFrame {
Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    String sql = null;
    PreparedStatement pst = null;
    /**
     * Creates new form cash_in
     */
    public cash_in() {
        initComponents();
        conn = connector.connectiondb();
        this.setLocationRelativeTo(null);
        btn_cashin.setEnabled(false);
       

        new Thread(){
            public void run(){
            while(true){
                Date dNow = new Date ( );
            
            SimpleDateFormat ft = new SimpleDateFormat (" yyyy-MM-dd");
            String time = ""+ft.format(dNow);
            date.setText(time);
            }
                }
        }.start();
        
        ImageIcon myimage62 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("savedme-logo.JPG")));     
      Image img11 = myimage62.getImage();
      Image img12 = img11.getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(), Image.SCALE_SMOOTH);
      ImageIcon e = new ImageIcon(img12);
    jLabel1.setIcon(e);
    
    ImageIcon myimage6a = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("cashin.png")));     
      Image img1a = myimage6a.getImage();
      Image img12a = img1a.getScaledInstance(cashi.getWidth(),cashi.getHeight(), Image.SCALE_SMOOTH);
      ImageIcon evo = new ImageIcon(img12a);
    cashi.setIcon(evo);
    
    
     }
    
     private void datas(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/savedme_db","root","");
        String sql = "select distinct id AS ID, concat(fname,' ',mname,' ',lname) as NAME, sum(cash_in.amount) AS ASSETS, shares as SHARES from people inner join cash_in where people.id = cash_in.student group by cash_in.student ";
        PreparedStatement pstmt = con.prepareStatement(sql);
        ResultSet rs = pstmt.executeQuery();
        datas.setModel(DbUtils.resultSetToTableModel(rs));
    
    }catch (ClassNotFoundException | SQLException v){
        JOptionPane.showMessageDialog(null, v);}}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        student_id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        shares = new javax.swing.JLabel();
        asd = new javax.swing.JLabel();
        birth = new javax.swing.JLabel();
        area2 = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        sa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cashi = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        area1 = new javax.swing.JLabel();
        fullname = new javax.swing.JLabel();
        shopname2 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        gender = new javax.swing.JLabel();
        btn_cashin = new javax.swing.JButton();
        date = new javax.swing.JLabel();
        myref = new javax.swing.JLabel();
        shopname3 = new javax.swing.JLabel();
        myasset = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/savedme-logo.JPG"))); // NOI18N
        jLabel1.setText("Logo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 160, 50));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 0, 0));
        jLabel25.setText("CLOSE");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 40, -1));

        jLabel2.setText("____________________________________________________________________");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 94, 490, -1));

        student_id.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        student_id.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.lightGray));
        student_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                student_idKeyReleased(evt);
            }
        });
        jPanel1.add(student_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 230, 30));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jLabel7.setText("Student ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 210, 20));

        shares.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 12)); // NOI18N
        shares.setText("2%");
        jPanel1.add(shares, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 100, 20));

        asd.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        asd.setForeground(new java.awt.Color(0, 102, 0));
        asd.setText("Ref #    :");
        jPanel1.add(asd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 50, 20));

        birth.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        birth.setText("Birth");
        jPanel1.add(birth, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 210, 20));

        area2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        area2.setForeground(new java.awt.Color(102, 102, 102));
        area2.setText("Email    :");
        jPanel1.add(area2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 50, 20));

        phone.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        phone.setText("###");
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 160, 20));

        sa.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        sa.setForeground(new java.awt.Color(102, 102, 102));
        sa.setText("Phone  : ");
        jPanel1.add(sa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 50, 20));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel3.setText("CASH-IN");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 67, 130, 40));

        cashi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/cashin.png"))); // NOI18N
        cashi.setText("cash");
        jPanel1.add(cashi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 40, 30));

        email.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        email.setText("@mail.com");
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 160, 20));

        area1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        area1.setText("Amount  :");
        jPanel1.add(area1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 70, 30));

        fullname.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        fullname.setText("Fullname");
        jPanel1.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 210, 20));

        shopname2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 12)); // NOI18N
        shopname2.setText("Shares            :");
        jPanel1.add(shopname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 90, 20));
        jPanel1.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 110, 30));

        gender.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        gender.setText("Gender");
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 210, 20));

        btn_cashin.setBackground(new java.awt.Color(0, 204, 0));
        btn_cashin.setForeground(new java.awt.Color(255, 255, 255));
        btn_cashin.setText("Cash in");
        btn_cashin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cashin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cashinActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cashin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 180, 40));

        date.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        date.setText("Date");
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 84, 160, 20));

        myref.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        myref.setForeground(new java.awt.Color(0, 102, 0));
        myref.setText("###");
        jPanel1.add(myref, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 160, 20));

        shopname3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        shopname3.setText("Your Asset     :");
        jPanel1.add(shopname3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 90, 20));

        myasset.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        myasset.setText("0.00");
        jPanel1.add(myasset, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 100, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel25MouseClicked

    private void student_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_student_idKeyReleased

        if(student_id.getText().equals(""))
        {
            fullname.setText("Fullname");
            gender.setText("Gender");
            birth.setText("Birth");
            email.setText("@mail.com");
            phone.setText("###");
            myref.setText("###");
            btn_cashin.setEnabled(false);
               
        }

        try{

            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/savedme_db","root","");

            String sq = "SELECT concat(`fname`,' ',`mname`,' ',`lname`) as fullname, birth, gender, email, phone, reference,status from people where id = ? and role = 'Student'  ";
            pst = conn.prepareStatement(sq);
            pst.setString(1, student_id.getText());

            rs = pst.executeQuery();

            if(rs.next()){
                String add1=rs.getString("fullname");
                fullname.setText(add1);

                String add2=rs.getString("gender");
                gender.setText(add2);

                String add3=rs.getString("birth");
                birth.setText(add3);

                String add4=rs.getString("email");
                email.setText(add4);

                String add5=rs.getString("phone");
                phone.setText(add5);
                
                String add6=rs.getString("reference");
                myref.setText(add6);
                
                String add7=rs.getString("status");

                btn_cashin.setEnabled(true);    
                
                if(("Cashout") != add7)
                {
                } else {
                    
                    btn_cashin.setEnabled(false);
                }
                
            }
            
            
            else{

               fullname.setText("Fullname");
            gender.setText("Gender");
            birth.setText("Birth");
            email.setText("@mail.com");
            phone.setText("###");
            myref.setText("###");
            btn_cashin.setEnabled(false);
            }

        }catch (ClassNotFoundException | SQLException e)
        {JOptionPane.showMessageDialog(null, e);}
         try{
      Class.forName("com.mysql.jdbc.Driver");
      conn = DriverManager.getConnection("jdbc:mysql://localhost/savedme_db","root","");

            String sq = "select sum(amount) as myasset  from cash_in where student = ? ";
            pst = conn.prepareStatement(sq);
            pst.setString(1, student_id.getText());
            rs = pst.executeQuery();
            
          
                if(rs.next()){ 
              String add1=rs.getString("myasset");
              myasset.setText(add1);                       
            
                }
                
        }catch (ClassNotFoundException | SQLException b)
        {{JOptionPane.showMessageDialog(null, b);}
        }
         
    }//GEN-LAST:event_student_idKeyReleased

    private void btn_cashinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cashinActionPerformed

            try{

                String Sql= "INSERT INTO `cash_in`(`date`, `student`, `reference`, `amount`,shares) VALUES  (?,?,?,?,?)";
                pst= conn.prepareStatement(Sql);

                pst.setString(1, date.getText());
                pst.setString(2, student_id.getText());
                pst.setString(3, myref.getText());
                pst.setString(4,amount.getText());
                pst.setString(5,shares.getText());
                        

                if(JOptionPane.showConfirmDialog(null,"Confirm?","Cash-in",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
                {
                    pst.execute();                 
                    JOptionPane.showMessageDialog(null,"Done.");
                   amount.setText("");
                   datas();
                    try{
      Class.forName("com.mysql.jdbc.Driver");
      conn = DriverManager.getConnection("jdbc:mysql://localhost/savedme_db","root","");

            String sq = "select sum(amount) as myasset  from cash_in where student = ? ";
            pst = conn.prepareStatement(sq);
            pst.setString(1, student_id.getText());
            rs = pst.executeQuery();
            
          if(rs.next()){ 
                
              String add1=rs.getString("myasset");
              myasset.setText(add1);  
          }
            
        }catch (ClassNotFoundException | SQLException b)
        {
        } 
        

           
                }
               }

                catch(SQLException | HeadlessException e){
                    JOptionPane.showMessageDialog(null, "Error.","ERROR",2);
                }

            
    }//GEN-LAST:event_btn_cashinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cash_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cash_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cash_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cash_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cash_in().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JLabel area1;
    private javax.swing.JLabel area2;
    private javax.swing.JLabel asd;
    private javax.swing.JLabel birth;
    private javax.swing.JButton btn_cashin;
    private javax.swing.JLabel cashi;
    private javax.swing.JLabel date;
    private javax.swing.JLabel email;
    private javax.swing.JLabel fullname;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel myasset;
    private javax.swing.JLabel myref;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel sa;
    private javax.swing.JLabel shares;
    private javax.swing.JLabel shopname2;
    private javax.swing.JLabel shopname3;
    private javax.swing.JTextField student_id;
    // End of variables declaration//GEN-END:variables
}
