/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static login.adminpanel.myid;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author lenovo
 */
public class cashout extends javax.swing.JFrame {
Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    String sql = null;
    PreparedStatement pst = null;
    /**
     * Creates new form cashout
     */
    public cashout() {
        initComponents();
        conn = connector.connectiondb();
        this.setLocationRelativeTo(null);
         btn_withdraw.setEnabled(false);
         stat.setVisible(false);
        
        ImageIcon myimage62 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("savedme-logo.JPG")));     
      Image img11 = myimage62.getImage();
      Image img12 = img11.getScaledInstance(jLabel7.getWidth(),jLabel7.getHeight(), Image.SCALE_SMOOTH);
      ImageIcon e = new ImageIcon(img12);
    jLabel7.setIcon(e);
    
    new Thread(){
            public void run(){
            while(true){
                Date dNow = new Date ( );
            
            SimpleDateFormat ft = new SimpleDateFormat (" yyyy-MM-dd");
            String time = ""+ft.format(dNow);
            date.setText(time);
            }
                }
        }.start();
    
    try{

      
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/savedme_db","root","");

            String sq = "select concat(fname,' ',mname,' ',lname) as cashier from people  where  id= ? and role = 'Admin' ";
            pst = conn.prepareStatement(sq);
            pst.setString(1, myid.getText());

            rs = pst.executeQuery();

            if(rs.next()){

                String add1=rs.getString("cashier");
                cashier.setText(add1);
       }

        }catch (ClassNotFoundException | SQLException ep)
        {
            JOptionPane.showMessageDialog(null ,ep);
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        reference = new javax.swing.JLabel();
        fullname = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        w_id = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        w_datas_table = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btn_withdraw = new javax.swing.JButton();
        cashier = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        stat = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        birth = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/savedme-logo.JPG"))); // NOI18N
        jLabel7.setText("logo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Reference #:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 90, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("ID No.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Email :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Name :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 125, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Sex :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 50, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Phone :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 185, -1, 20));

        reference.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        reference.setText("-");
        jPanel1.add(reference, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 220, 20));

        fullname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fullname.setText("-");
        jPanel1.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 220, 20));

        gender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gender.setText("-");
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 70, 20));

        phone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        phone.setText("-");
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 220, 20));

        email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        email.setText("-");
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 220, 20));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("X");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 7, 30, 30));

        w_id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        w_id.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.lightGray, java.awt.Color.darkGray));
        w_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                w_idActionPerformed(evt);
            }
        });
        w_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                w_idKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                w_idKeyReleased(evt);
            }
        });
        jPanel1.add(w_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 81, 200, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        w_datas_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(w_datas_table);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 250, 410));

        n_recievable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        n_recievable.setText("0.00");
        jPanel2.add(n_recievable, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 100, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("RECORD");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 80, 30));

        n_profit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        n_profit.setText("0.00");
        jPanel2.add(n_profit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 70, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel16.setText("2%");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 30, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel17.setText("Shares  :");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 60, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Asset :");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 50, 30));

        n_total.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        n_total.setText("0.00");
        jPanel2.add(n_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 100, 30));

        btn_withdraw.setBackground(new java.awt.Color(0, 204, 204));
        btn_withdraw.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btn_withdraw.setText("Withdraw");
        btn_withdraw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_withdrawActionPerformed(evt);
            }
        });
        jPanel2.add(btn_withdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 397, 110, 40));

        cashier.setText("Name");
        jPanel2.add(cashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 160, 20));

        jLabel19.setText(" Assested By :");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 80, 20));

        jLabel20.setText("Date :");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 40, 20));

        date.setText("Date");
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 160, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Recievable :");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 80, 30));

        stat.setFont(new java.awt.Font("Viner Hand ITC", 3, 48)); // NOI18N
        stat.setForeground(new java.awt.Color(0, 0, 255));
        stat.setText("CASH OUT !");
        jPanel2.add(stat, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 360, 110));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 730, 450));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Birth Date: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 70, 20));

        birth.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        birth.setText("-");
        jPanel1.add(birth, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 140, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void w_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_w_idKeyPressed
      try{
        Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/savedme_db","root","");
        String sql = "select cash_in.date as Date,  cash_in.amount as Amount from cash_in inner join people where people.id = ? and cash_in.reference = people.reference order by date desc ";
        pst = conn.prepareStatement(sql);
            pst.setString(1, w_id.getText());

            rs = pst.executeQuery();
        w_datas_table.setModel(DbUtils.resultSetToTableModel(rs));
    
    }catch (ClassNotFoundException | SQLException v){
       }
      
            
      
      
    }//GEN-LAST:event_w_idKeyPressed

    private void w_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_w_idKeyReleased
     if(w_id.getText().equals(""))
        {
            fullname.setText("-");
            gender.setText("-");
            phone.setText("-");
            email.setText("-");
            reference.setText("-");    
            birth.setText("-");
            n_total.setText("0.00");
            n_profit.setText("0.00");
            n_recievable.setText("0.00");
            stat.setVisible(false);
            btn_withdraw.setEnabled(false);
        }

        try{

            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/savedme_db","root","");

            String sq = " SELECT concat(`fname`,' ',`mname`,' ',`lname`) as fullname, birth, gender, email, phone, reference,status from people where id = ? and role = 'Student' ";
            pst = conn.prepareStatement(sq);
            pst.setString(1, w_id.getText());

            rs = pst.executeQuery();
            btn_withdraw.setEnabled(true);
            if(rs.next()){
                String add1=rs.getString("fullname");
                fullname.setText(add1);

                String add2=rs.getString("birth");
                birth.setText(add2);

                String add3=rs.getString("gender");
                gender.setText(add3);

                String add4=rs.getString("phone");
                phone.setText(add4);

                String add5=rs.getString("email");
                email.setText(add5);
                
                String add6=rs.getString("reference");
                reference.setText(add6);
                
                String add7=rs.getString("status");
                if(!"Cashout".equals(add7))
                {
                } else {
                    stat.setVisible(true);
                    btn_withdraw.setEnabled(false);
                }
                
                
            }
            else{

        fullname.setText("-");
            gender.setText("-");
            phone.setText("-");
            email.setText("-");
            reference.setText("-");    
            birth.setText("-");
            n_total.setText("0.00");
            n_profit.setText("0.00");
            n_recievable.setText("0.00");
            btn_withdraw.setEnabled(false);
            stat.setVisible(false);
            }

        }catch (ClassNotFoundException | SQLException e)
        {JOptionPane.showMessageDialog(null, e);}
        
        
    }//GEN-LAST:event_w_idKeyReleased

    private void w_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_w_idActionPerformed
      try{  
            String vb = w_id.getText();
            String sql = "select  sum(cash_in.amount) as n_sum  from cash_in inner join people where people.id = '"+vb+"' and cash_in.reference = people.reference ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if(rs.next())
            {                             
              String add2=rs.getString("n_sum");
             if(add2 == null){
                 
             }else{
             n_total.setText(add2); 

                      double a = Double.parseDouble(add2);
              
              double ans= 0;
                      ans = a * 0.2;
             NumberFormat nf2 = NumberFormat.getInstance(new Locale("en", "US"));
             String val2 = nf2.format(ans);
              n_profit.setText(val2);
           
              float ans2 = (float) (a + ans);
              NumberFormat nf3 = NumberFormat.getInstance(new Locale("en", "US"));
              String val3 = nf3.format(ans2);
              n_recievable.setText(val3);

            }}
            else{
                
            }

        }catch(SQLException exz){}
    }//GEN-LAST:event_w_idActionPerformed

    private void btn_withdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_withdrawActionPerformed
   try{
                String Sql= "INSERT INTO `cashout`(`cashier`, `student`, `asset`, `profit`, `recievable`, `date`) VALUES  (?,?,?,?,?,?)";
                pst= conn.prepareStatement(Sql);

                pst.setString(1, myid.getText());
                pst.setString(2, w_id.getText());
                pst.setString(3, n_total.getText());
                pst.setString(4,n_profit.getText());
                pst.setString(5,n_recievable.getText());
                pst.setString(6,date.getText());
                        
                if(JOptionPane.showConfirmDialog(null,"Confirm?","Cash Out",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
                {
                    pst.execute();                 
                                      
                   try{  String sql="DELETE FROM `cash_in` WHERE student = ?";
                pst=conn.prepareStatement(sql);
                pst.setString(1,w_id.getText());
                pst.execute();
                
                JOptionPane.showMessageDialog(null,"Done.");

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);}
        
try{
                 String value1 = w_id.getText();
                 String j = "Cashout";
                String sql2 = "UPDATE `people` SET `status`=? WHERE id = '"+value1+"'";
                pst=conn.prepareStatement(sql2);
                pst.setString(1,j);                                                                                         
                pst.execute();

            }catch(Exception eh){
                JOptionPane.showMessageDialog(null, eh);
           }
           }
           }

                catch(SQLException | HeadlessException eu){
                    JOptionPane.showMessageDialog(null,eu);
                }
    }//GEN-LAST:event_btn_withdrawActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cashout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cashout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cashout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cashout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cashout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birth;
    private javax.swing.JButton btn_withdraw;
    private javax.swing.JLabel cashier;
    private javax.swing.JLabel date;
    private javax.swing.JLabel email;
    private javax.swing.JLabel fullname;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static final javax.swing.JLabel n_profit = new javax.swing.JLabel();
    public static final javax.swing.JLabel n_recievable = new javax.swing.JLabel();
    public static final javax.swing.JLabel n_total = new javax.swing.JLabel();
    private javax.swing.JLabel phone;
    private javax.swing.JLabel reference;
    private javax.swing.JLabel stat;
    private javax.swing.JTable w_datas_table;
    private javax.swing.JTextField w_id;
    // End of variables declaration//GEN-END:variables
}
