/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static login.adminpanel.invoice_table;
import static login.adminpanel.total;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author lenovo
 */
public class invoice extends javax.swing.JFrame {
Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    String sql = null;
    PreparedStatement pst = null;
    /**
     * Creates new form invoice
     */
    public invoice() {
        initComponents();
        conn = connector.connectiondb();
        this.setLocationRelativeTo(null);
        btnsave.setEnabled(false);
        
        
        new Thread(){
            public void run(){
            while(true){
                Date dNow = new Date ( );
            
            SimpleDateFormat ft = new SimpleDateFormat (" yyyy-MM-dd");
            String time = ""+ft.format(dNow);
            date.setText(time);
            }
                }
        }.start();
        
        ImageIcon myimage62 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("savedme-logo.JPG")));     
      Image img11 = myimage62.getImage();
      Image img12 = img11.getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(), Image.SCALE_SMOOTH);
      ImageIcon e = new ImageIcon(img12);
    jLabel1.setIcon(e);
    
    
    try{
      Class.forName("com.mysql.jdbc.Driver");
      conn = DriverManager.getConnection("jdbc:mysql://localhost/savedme_db","root","");

            String sq = "select invoice_no  from invoice order by invoice_no desc limit 1 ";
            pst = conn.prepareStatement(sq);           
            rs = pst.executeQuery();
            
            if(rs.next()){   
                
              String add1=rs.getString("invoice_no");
                int sum=0;
                int a = Integer.parseInt(add1);
                sum=a+1;
                invoiceno.setText(Integer.toString(sum));   
            }
            
        }catch (ClassNotFoundException | SQLException b)
        {
        } 
   
    }
    private void invoice_table(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/savedme_db","root","");
        String sql = "Select invoice.date as DATE, invoice.invoice_no AS INVOICE,  concat(shop.shopname,' - ', invoice.shopid) AS SHOP, invoice.refno AS REFERENCE, invoice.signed AS SIGNED, invoice.cash AS CASH from invoice INNER JOIN shop where invoice.shipto = 'USTP Accounting Office' AND invoice.shopid = shop.shopid GROUP BY invoice.invoice_no ORDER BY invoice.invoice_no desc ";
        PreparedStatement pstmt = con.prepareStatement(sql);
        ResultSet rs = pstmt.executeQuery();
        invoice_table.setModel(DbUtils.resultSetToTableModel(rs));
    
    }catch (ClassNotFoundException | SQLException v){
        JOptionPane.showMessageDialog(null, v);}}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        invoiceno = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        shopid = new javax.swing.JTextField();
        phone = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        shopname = new javax.swing.JLabel();
        recipient = new javax.swing.JLabel();
        shipto = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        refno = new javax.swing.JLabel();
        sa = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        cash = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        signed = new com.toedter.calendar.JDateChooser();
        area = new javax.swing.JLabel();
        area2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/savedme-logo.JPG"))); // NOI18N
        jLabel1.setText("Logo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 180, 50));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 30)); // NOI18N
        jLabel3.setText("INVOICE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 130, 40));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel4.setText("Misamis Occidental, PH");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 140, 20));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel5.setText("0906 290 5452");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 140, 20));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel6.setText("aquit.reynaldo@gmail.com");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 160, 20));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jLabel7.setText("Shop #");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 210, 20));

        date.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        date.setText("DATE");
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 140, 20));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel10.setText("Punta, Panaon 7205");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 140, 20));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 255));
        jLabel12.setText("Invoice # :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 60, 20));

        invoiceno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        invoiceno.setForeground(new java.awt.Color(0, 51, 255));
        invoiceno.setText("###");
        jPanel1.add(invoiceno, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 140, 20));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel14.setText("DATE       :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 60, 20));

        shopid.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        shopid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.lightGray));
        shopid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                shopidKeyReleased(evt);
            }
        });
        jPanel1.add(shopid, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 230, 30));

        phone.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 102, 0));
        phone.setText("###");
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 160, 20));

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(0, 0, 255));
        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("BILL TO");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 230, 20));

        jPanel3.setBackground(new java.awt.Color(0, 51, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SHIP TO");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue));
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 230, 20));

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel15.setText("savedme-fis.ph");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 210, 20));

        shopname.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        shopname.setText("Name of the Shop");
        jPanel1.add(shopname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 210, 20));

        recipient.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        recipient.setForeground(new java.awt.Color(255, 102, 0));
        recipient.setText("Recipient");
        jPanel1.add(recipient, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 210, 20));

        shipto.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        shipto.setText("USTP Accounting Office");
        jPanel1.add(shipto, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 150, 20));

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel20.setText("ustp.accountingoffice@email.com");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 200, 20));

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel21.setText("Punta, Panaon 7205");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 140, 20));

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabel22.setText("Misamis Occidental, PH");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 140, 20));

        btnsave.setBackground(new java.awt.Color(0, 255, 51));
        btnsave.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        btnsave.setForeground(new java.awt.Color(255, 255, 255));
        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, 160, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 0, 0));
        jLabel25.setText("CLOSE");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 10, 40, -1));

        refno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        refno.setForeground(new java.awt.Color(255, 102, 0));
        refno.setText("###");
        jPanel1.add(refno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 160, 20));

        sa.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        sa.setForeground(new java.awt.Color(255, 102, 0));
        sa.setText("Phone#: ");
        jPanel1.add(sa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 50, 20));

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cash.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.add(cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 170, 30));

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 11)); // NOI18N
        jLabel17.setText("Signed Date :");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, 30));

        jLabel28.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel28.setText("Cash :");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 30));

        signed.setDateFormatString("yyyy-MM-dd");
        jPanel4.add(signed, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 170, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 280, 110));

        area.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        area.setText("Area");
        jPanel1.add(area, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 210, 20));

        area2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        area2.setForeground(new java.awt.Color(255, 102, 0));
        area2.setText("Ref#     : ");
        jPanel1.add(area2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 50, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel25MouseClicked

    private void shopidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_shopidKeyReleased
        
        if(shopid.getText().equals(""))
        {
            shopname.setText("Name of the Shop");
            area.setText("Area");
            recipient.setText("Recipient");
            refno.setText("###");
            phone.setText("###");    
            btnsave.setEnabled(false);
        }

        try{

            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/savedme_db","root","");

            String sq = "select shopname, area, concat(people.fname,' ',people.mname,' ',people.lname) as recipient, reference, phone  from shop inner join people where shopid = ? and shop.employee = people.id  ";
            pst = conn.prepareStatement(sq);
            pst.setString(1, shopid.getText());

            rs = pst.executeQuery();

            if(rs.next()){
                String add1=rs.getString("shopname");
                shopname.setText(add1);

                String add2=rs.getString("area");
                area.setText(add2);

                String add3=rs.getString("recipient");
                recipient.setText(add3);

                String add4=rs.getString("reference");
                refno.setText(add4);

                String add5=rs.getString("phone");
                phone.setText(add5);
                
                btnsave.setEnabled(true);
            }
            else{

            shopname.setText("Name of the Shop");
            area.setText("Area");
            recipient.setText("Recipient");
            refno.setText("###");
            phone.setText("###");  
            btnsave.setEnabled(false);
            }

        }catch (Exception e)
        {JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_shopidKeyReleased

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
  
        if(shopid.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Shop Information is Required","Invalid",2);
        }
        else if(cash.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Cash Amount is *missing","Invalid",2);
        }

        else{
            try{

                String Sql= "INSERT INTO `invoice`(`invoice_no`, `shopid`, `refno`, `cash`, `signed`, `date`, `shipto`) VALUES  (?,?,?,?,?,?,?)";
                pst= conn.prepareStatement(Sql);

                pst.setString(1, invoiceno.getText());
                pst.setString(2, shopid.getText());
                pst.setString(3, refno.getText());
                pst.setString(4,cash.getText());              
                pst.setString(5,((JTextField)signed.getDateEditor().getUiComponent()).getText());
                pst.setString(6,date.getText());
                pst.setString(7,shipto.getText());


                if(JOptionPane.showConfirmDialog(null,"Confirm?","Invoice",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
                {
                    pst.execute();                 
                    JOptionPane.showMessageDialog(null,"Done.");
                   
                    try{
      Class.forName("com.mysql.jdbc.Driver");
      conn = DriverManager.getConnection("jdbc:mysql://localhost/savedme_db","root","");

            String sq = "select invoice_no  from invoice order by invoice_no desc limit 1 ";
            pst = conn.prepareStatement(sq);           
            rs = pst.executeQuery();
            
            if(rs.next()){   
                
              String add1=rs.getString("invoice_no");
                int sum=0;
                int a = Integer.parseInt(add1);
                sum=a+1;
                invoiceno.setText(Integer.toString(sum));  
            }
            
        }catch (ClassNotFoundException | SQLException b)
        {
        } 
        try{
      Class.forName("com.mysql.jdbc.Driver");
      conn = DriverManager.getConnection("jdbc:mysql://localhost/savedme_db","root","");

            String sq = "select sum(cash) as total  from invoice ";
            pst = conn.prepareStatement(sq);           
            rs = pst.executeQuery();
            
            if(rs.next()){   
                
              String add2=rs.getString("total");
              total.setText(add2);   
            }
            
        }catch (ClassNotFoundException | SQLException n)
        {
        } 

            shopname.setText("Name of the Shop");
            area.setText("Area");
            recipient.setText("Recipient");
            refno.setText("###");
            phone.setText("###");  
            btnsave.setEnabled(false);
            cash.setText("");
            shopid.setText("");
           invoice_table();
                }
                else
                {
                }}

                catch(SQLException | HeadlessException e){
                    JOptionPane.showMessageDialog(null, "Error.","ERROR",2);
                }

            }

    }//GEN-LAST:event_btnsaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new invoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel area;
    private javax.swing.JLabel area2;
    private javax.swing.JButton btnsave;
    private javax.swing.JTextField cash;
    private javax.swing.JLabel date;
    private javax.swing.JLabel invoiceno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel recipient;
    private javax.swing.JLabel refno;
    private javax.swing.JLabel sa;
    private javax.swing.JLabel shipto;
    private javax.swing.JTextField shopid;
    private javax.swing.JLabel shopname;
    private com.toedter.calendar.JDateChooser signed;
    // End of variables declaration//GEN-END:variables
}
