/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static login.adminpanel.myid;
import static login.adminpanel.profilepic;
import static login.myaddress.mycity;
import static login.myaddress.myprov;
import static login.myaddress.myzipcode;
import static login.myaddress.myno;


/**
 *
 * @author lenovo
 */
public class myprofile extends javax.swing.JFrame {
Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    String sql = null;
    PreparedStatement pst = null;
  
    String filename = null;
    byte[] person_image = null;
    /**
     * Creates new form myprofile
     */
    public myprofile() {

        initComponents();
        conn = connector.connectiondb();
        this.setLocationRelativeTo(null);
  
        phone.setBackground(new Color(214, 212, 212));
        email.setBackground(new Color(214, 212, 212));
        
        ImageIcon myimage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons8_home_address_32.png")));     
      Image img = myimage.getImage();
      Image img1 = img.getScaledInstance(wrt.getWidth(),wrt.getHeight(), Image.SCALE_SMOOTH);
      ImageIcon e = new ImageIcon(img1);
    wrt.setIcon(e);
    
    ImageIcon myimage2 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons8_phone_32.png")));     
      Image imga = myimage2.getImage();
      Image img22 = imga.getScaledInstance(phon.getWidth(),phon.getHeight(), Image.SCALE_SMOOTH);
      ImageIcon v = new ImageIcon(img22);
    phon.setIcon(v);
    
    ImageIcon myimage3 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons8_email_32.png")));     
      Image imgb = myimage3.getImage();
      Image img33 = imgb.getScaledInstance(mail.getWidth(),mail.getHeight(), Image.SCALE_SMOOTH);
      ImageIcon c = new ImageIcon(img33);
    mail.setIcon(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        profilesec = new javax.swing.JLabel();
        uploadphoto = new javax.swing.JButton();
        savechanges = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        phon = new javax.swing.JLabel();
        wrt = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.orange, java.awt.Color.orange));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profilesec.setForeground(new java.awt.Color(255, 255, 255));
        profilesec.setText("photo");
        profilesec.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.white));
        jPanel1.add(profilesec, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 91, 86));

        uploadphoto.setBackground(new java.awt.Color(255, 255, 255));
        uploadphoto.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        uploadphoto.setText("Change Photo");
        uploadphoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uploadphoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadphotoActionPerformed(evt);
            }
        });
        jPanel1.add(uploadphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 55, 110, 20));

        savechanges.setBackground(new java.awt.Color(255, 255, 255));
        savechanges.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        savechanges.setText("Save Changes");
        savechanges.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        savechanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savechangesActionPerformed(evt);
            }
        });
        jPanel1.add(savechanges, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 78, 110, 20));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CLOSE");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        role.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        role.setForeground(new java.awt.Color(255, 255, 255));
        role.setText("Role");
        jPanel1.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 390, 30));

        fullname.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        fullname.setForeground(new java.awt.Color(255, 255, 255));
        fullname.setText("Fullname");
        jPanel1.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 390, 30));

        gender.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        gender.setForeground(new java.awt.Color(255, 255, 255));
        gender.setText("Gender");
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 390, 30));

        birth.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        birth.setForeground(new java.awt.Color(255, 255, 255));
        birth.setText("Birth");
        jPanel1.add(birth, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 390, 30));

        jButton2.setBackground(new java.awt.Color(0, 0, 255));
        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update Info");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 140, -1));

        phon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/icons8_phone_32.png"))); // NOI18N
        phon.setText("wrt");
        jPanel1.add(phon, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 20, 20));

        email.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        email.setText("Email");
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 220, 30));

        phone.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        phone.setText("Phone");
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 220, 30));

        wrt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/icons8_home_address_32.png"))); // NOI18N
        wrt.setText("wrt");
        wrt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        wrt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wrtMouseClicked(evt);
            }
        });
        jPanel1.add(wrt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 30, 30));

        mail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/icons8_email_32.png"))); // NOI18N
        mail.setText("wrt");
        jPanel1.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 20, 20));

        address.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        address.setForeground(new java.awt.Color(255, 255, 255));
        address.setText("Address");
        address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 380, 30));

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jButton3.setText("Change Password");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 140, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uploadphotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadphotoActionPerformed
 JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon (new ImageIcon(filename).getImage().getScaledInstance(profilesec.getWidth(),profilesec.getHeight(),Image.SCALE_SMOOTH));
        profilesec.setIcon(imageIcon);
        
        try{
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for(int readNum; (readNum=fis.read(buf))!=-1;){
                bos.write(buf,0,readNum);
            }
            person_image=bos.toByteArray();
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_uploadphotoActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void savechangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savechangesActionPerformed
try{   
    byte[] imageBytes;
              Image images;
              
     File image = new File(filename);      
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
        
                String value1 = myid.getText();
                String Sql= "update people set profpic=? where id=" +value1;

            pst= conn.prepareStatement(Sql);              
            pst.setBytes(1,person_image);                  
            JOptionPane.showMessageDialog(null,"Save changes.");
            pst.executeUpdate();
            person_image=bos.toByteArray();
                    }
            catch(SQLException | HeadlessException e){JOptionPane.showMessageDialog(null, e);}

  try{
              byte[] imageBytes;
              Image image;
      
            
                    Class.forName("com.mysql.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost/savedme_db","root","");

            String sq = "select * from people where  id= ?";
            pst = conn.prepareStatement(sq);
            pst.setString(1, myid.getText());
            
            rs = pst.executeQuery();
            
            if(rs.next()){
            
             imageBytes=rs.getBytes("profpic");
                image=getToolkit().createImage(imageBytes);
                ImageIcon icon=new ImageIcon(image);             
                 ImageIcon imageIcon = new ImageIcon (new     ImageIcon(image).getImage().getScaledInstance(profilepic.getWidth(),profilepic.getHeight(),Image.SCALE_SMOOTH));
                profilepic.setIcon(imageIcon);
                 
                    
            
            }
            
        }catch (Exception e)
        {
        }        // TODO add your handling code here:
    }//GEN-LAST:event_savechangesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
         if(phone.getText().equals(""))
        {JOptionPane.showMessageDialog(null, "No changes. 'Phone' ");}
          if(email.getText().equals(""))
        {JOptionPane.showMessageDialog(null, "No changes. 'e-mail' ");}
        else{
            try{
                  String value1 = myid.getText();
                String sql = "UPDATE `people` SET `phone`=?,`email`=? WHERE id = '"+value1+"'";
                pst=conn.prepareStatement(sql);

                pst.setString(1,phone.getText());                                        
                pst.setString(2, email.getText());                                                    
                
                JOptionPane.showMessageDialog(null, "Update success!");
                pst.execute();

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void wrtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wrtMouseClicked
 /*myaddress p = new myaddress();
            p.setVisible(true);*/
            
    try{         
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/savedme_db","root","");

            String sq = "select people.zipcode, address.city, address.province, address.no from people inner join address where  id= ? and address.zipcode = people.zipcode ";
            pst = conn.prepareStatement(sq);
            pst.setString(1, myid.getText());

            rs = pst.executeQuery();

            if(rs.next()){
                
                String add=rs.getString("no");
                myno.setText(add);

                String add1=rs.getString("zipcode");
                myzipcode.setText(add1);  

                String add2=rs.getString("city");
                mycity.setText(add2);

                String add3=rs.getString("province");
                myprov.setText(add3);                    
            }

        }catch (Exception e)
        {
           // JOptionPane.showMessageDialog(null ,e);
        }         
        
    }//GEN-LAST:event_wrtMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        config p = new config();
            p.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myprofile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JLabel address = new javax.swing.JLabel();
    public static final javax.swing.JLabel birth = new javax.swing.JLabel();
    public static final javax.swing.JTextField email = new javax.swing.JTextField();
    public static final javax.swing.JLabel fullname = new javax.swing.JLabel();
    public static final javax.swing.JLabel gender = new javax.swing.JLabel();
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mail;
    private javax.swing.JLabel phon;
    public static final javax.swing.JTextField phone = new javax.swing.JTextField();
    private javax.swing.JLabel profilesec;
    public static final javax.swing.JLabel role = new javax.swing.JLabel();
    private javax.swing.JButton savechanges;
    private javax.swing.JButton uploadphoto;
    private javax.swing.JLabel wrt;
    // End of variables declaration//GEN-END:variables
}
