/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author lenovo
 */
public class n_datas extends javax.swing.JFrame {
Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    String sql = null;
    PreparedStatement pst = null;
    /**
     * Creates new form n_datas
     */
    public n_datas() {
        initComponents();
        conn = connector.connectiondb();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Asset = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Asset.setBackground(new java.awt.Color(153, 153, 153));
        Asset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Asset.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        n_datas_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(n_datas_table);

        Asset.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 250, 390));

        n_ref.setForeground(new java.awt.Color(255, 255, 204));
        n_ref.setText("Reference#");
        Asset.add(n_ref, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 80, 200, -1));

        n_id.setForeground(new java.awt.Color(255, 255, 255));
        n_id.setText("ID#");
        Asset.add(n_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 230, -1));

        n_fullname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        n_fullname.setForeground(new java.awt.Color(255, 255, 255));
        n_fullname.setText("Name");
        Asset.add(n_fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 230, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("Ref:");
        Asset.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CLOSE");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        Asset.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        m_profit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        m_profit.setForeground(new java.awt.Color(153, 255, 255));
        m_profit.setText("0.00");
        Asset.add(m_profit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 70, 30));

        n_total.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        n_total.setForeground(new java.awt.Color(153, 255, 255));
        n_total.setText("0.00");
        Asset.add(n_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 100, 30));
        Asset.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 50, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 255));
        jLabel5.setText("Asset :");
        Asset.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 50, 30));

        m_recievable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        m_recievable.setForeground(new java.awt.Color(153, 255, 255));
        m_recievable.setText("0.00");
        Asset.add(m_recievable, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 100, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 255));
        jLabel7.setText("Shares  :");
        Asset.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 60, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 255));
        jLabel8.setText("Recievable :");
        Asset.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 80, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 255, 255));
        jLabel9.setText("2%");
        Asset.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Asset, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Asset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(n_datas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(n_datas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(n_datas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(n_datas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new n_datas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Asset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public static final javax.swing.JLabel m_profit = new javax.swing.JLabel();
    public static final javax.swing.JLabel m_recievable = new javax.swing.JLabel();
    public static final javax.swing.JTable n_datas_table = new javax.swing.JTable();
    public static final javax.swing.JLabel n_fullname = new javax.swing.JLabel();
    public static final javax.swing.JLabel n_id = new javax.swing.JLabel();
    public static final javax.swing.JLabel n_ref = new javax.swing.JLabel();
    public static final javax.swing.JLabel n_total = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
}
